#!/bin/sh
#
# pre-commit hook, runs before prompt for commit message
#

FULL_SCRIPT="./clean-cproj-for-commit.sh"

if [ -e $FULL_SCRIPT ] ; then
	exec "$FULL_SCRIPT"
else
	echo "Warning: Missing *.cproj cleaning script '$FULL_SCRIPT'. (Are you up to date with master?)"
fi
